"""Public contract of the invoices module.

Other modules may import only this file: DTOs, commands, queries and domain exceptions. Handlers
for these messages are registered in ``invoices.module``; ORM entities never leave the module.
"""

from dataclasses import dataclass
from datetime import date, datetime
from decimal import Decimal
from enum import StrEnum
from typing import Literal, get_args
from uuid import UUID

from time_reporting.core.cqrs import Command, Query
from time_reporting.modules.timesheets.contracts import BillingPeriodRef

type ClearableInvoiceField = Literal["vat_rate", "vat_note", "your_reference", "notes"]

# Optional fields that ``UpdateInvoiceDraft.clear_fields`` can reset to ``None``.
CLEARABLE_INVOICE_FIELDS: tuple[ClearableInvoiceField, ...] = get_args(
    ClearableInvoiceField.__value__
)


class InvoiceStatus(StrEnum):
    """An invoice's place in its lifecycle. ``DRAFT`` is mutable (header and lines);
    ``IssueInvoice`` moves it to ``ISSUED``, at which point it becomes immutable — only
    ``MarkInvoicePaid`` (→ ``PAID``) and ``VoidInvoice`` (→ ``VOID``, from ``ISSUED`` or ``PAID``)
    still change it, and only ``paid_on``/``voided_at``/``void_reason``."""

    DRAFT = "draft"
    ISSUED = "issued"
    PAID = "paid"
    VOID = "void"


class InvoiceLineKind(StrEnum):
    """Where a line came from. ``TIME`` and ``EXPENSE`` lines are generated by
    ``CreateInvoiceDraft`` from a billing period's export rows (see
    ``timesheets.contracts.GetBillingPeriodExportRows``); ``MANUAL`` lines are added free-form
    while the invoice is a draft."""

    TIME = "time"
    EXPENSE = "expense"
    MANUAL = "manual"


# --- DTOs ---


@dataclass(frozen=True, slots=True, kw_only=True)
class InvoiceCustomerDTO:
    """The subset of a draft's customer needed to display it alongside the invoice."""

    id: UUID
    name: str
    currency: str


@dataclass(frozen=True, slots=True, kw_only=True)
class InvoiceLineDTO:
    """One line of an invoice. ``project_id``/``billing_item_id`` are set only for a generated
    (``TIME``/``EXPENSE``) line — ``None`` for a ``MANUAL`` one. ``unit`` is free text (``"hour"``,
    ``"day"`` for a generated time line, ``"pcs"`` for a generated expense line or a manual one),
    not ``projects.contracts.BillingUnit`` — a manual line has no unit of its own to borrow.
    ``amount`` is always ``quantity * unit_price``, quantized to 0.01 (``ROUND_HALF_UP``)."""

    id: UUID
    position: int
    kind: InvoiceLineKind
    description: str
    quantity: Decimal
    unit: str
    unit_price: Decimal
    amount: Decimal
    project_id: UUID | None
    billing_item_id: UUID | None


@dataclass(frozen=True, slots=True, kw_only=True)
class InvoicePeriodDTO:
    """One billing period this invoice was built from (or still covers) — a
    ``timesheets.contracts.BillingPeriodRef`` plus display names, for the invoice detail page."""

    project_id: UUID
    project_name: str
    period_start: date


@dataclass(frozen=True, slots=True, kw_only=True)
class InvoiceDTO:
    id: UUID
    customer: InvoiceCustomerDTO
    status: InvoiceStatus
    # Allocated by IssueInvoice — ``None`` for every draft.
    number: str | None
    invoice_date: date
    due_date: date
    # ISO 4217, taken from the customer at creation.
    currency: str
    # "sv" or "en" — see ``customers.contracts.INVOICE_LOCALES``. Taken from the customer at
    # creation, falling back to the company default; always set (never ``None``) from then on.
    locale: str
    # ``None`` means no VAT line (e.g. reverse charge, explained instead via ``vat_note``).
    vat_rate: Decimal | None
    vat_note: str | None
    your_reference: str | None
    notes: str | None
    subtotal: Decimal
    vat_amount: Decimal
    total: Decimal
    issued_at: datetime | None
    paid_on: date | None
    voided_at: datetime | None
    void_reason: str | None
    lines: tuple[InvoiceLineDTO, ...]
    periods: tuple[InvoicePeriodDTO, ...]
    created_at: datetime
    updated_at: datetime


@dataclass(frozen=True, slots=True, kw_only=True)
class InvoiceSummaryDTO:
    """One row of a list view (``GET /invoices``)."""

    id: UUID
    customer_id: UUID
    customer_name: str
    status: InvoiceStatus
    number: str | None
    invoice_date: date
    due_date: date
    currency: str
    total: Decimal


@dataclass(frozen=True, slots=True, kw_only=True)
class InvoicePageDTO:
    items: tuple[InvoiceSummaryDTO, ...]
    total: int
    limit: int
    offset: int


@dataclass(frozen=True, slots=True, kw_only=True)
class InvoiceablePeriodDTO:
    """One sent, uninvoiced billing period of a customer, offered as a ``CreateInvoiceDraft``
    candidate."""

    project_id: UUID
    project_name: str
    period_start: date
    period_end: date
    sent_at: datetime


@dataclass(frozen=True, slots=True, kw_only=True)
class InvoiceableCustomerDTO:
    """One customer with at least one sent, uninvoiced billing period — the default selection for
    a new draft is every one of ``periods``."""

    customer_id: UUID
    customer_name: str
    currency: str
    periods: tuple[InvoiceablePeriodDTO, ...]


@dataclass(frozen=True, slots=True, kw_only=True)
class InvoicePdfDTO:
    """A rendered invoice PDF. For a draft, a fresh, unstored preview (``GetInvoicePdf`` renders it
    on every call, labeled "UTKAST/DRAFT"); for any other status, the bytes stored on the invoice
    at ``IssueInvoice`` time, served unchanged."""

    content: bytes
    filename: str


# --- Queries ---


@dataclass(frozen=True, slots=True, kw_only=True)
class GetInvoice(Query[InvoiceDTO]):
    """Raises ``InvoiceNotFoundError`` if ``invoice_id`` doesn't exist."""

    invoice_id: UUID


@dataclass(frozen=True, slots=True, kw_only=True)
class ListInvoices(Query[InvoicePageDTO]):
    """Invoices ordered by ``invoice_date`` (newest first), then id. Every filter is optional;
    ``date_from``/``date_to`` bound ``invoice_date`` inclusively."""

    customer_id: UUID | None = None
    status: InvoiceStatus | None = None
    date_from: date | None = None
    date_to: date | None = None
    limit: int
    offset: int


@dataclass(frozen=True, slots=True, kw_only=True)
class ListInvoiceablePeriods(Query[tuple[InvoiceableCustomerDTO, ...]]):
    """Every sent, uninvoiced, non-internal billing period, grouped by customer — built on
    ``timesheets.contracts.ListBillingPeriods(invoiced=False)``. A customer with no such period is
    absent from the result."""


@dataclass(frozen=True, slots=True, kw_only=True)
class CountInvoices(Query[int]):
    """How many invoices (any status) reference ``customer_id`` — used by the ``admin`` module's
    customer removal impact."""

    customer_id: UUID


@dataclass(frozen=True, slots=True, kw_only=True)
class GetInvoicePdf(Query[InvoicePdfDTO]):
    """Raises ``InvoiceNotFoundError`` if ``invoice_id`` doesn't exist. A query, not a command — a
    draft's preview render touches no persisted state."""

    invoice_id: UUID


# --- Commands ---


@dataclass(frozen=True, slots=True, kw_only=True)
class CreateInvoiceDraft(Command[InvoiceDTO]):
    """Build a draft invoice for ``customer_id`` from ``periods``, and mark each of them invoiced.

    Every period must be sent, not internal, not already invoiced, and belong to ``customer_id`` —
    checked for all of ``periods`` before anything is written. Raises
    ``InvoiceCustomerNotFoundError``, ``InvoiceNoPeriodsError`` (``periods`` is empty),
    ``InvoicePeriodNotEligibleError`` or ``BillingItemRateMissingError`` (some ``hour``/``day``
    billing item used in scope has no ``unit_rate`` — lists every such item; a missing
    ``markup_percent`` on an ``amount`` item is not an error, it just means no markup is applied).

    ``invoice_date`` is supplied by the router (``date.today()``), like
    ``timesheets.contracts.GetTeamMonthOverview.today`` — never computed inside the service, so
    tests can pin it.
    """

    customer_id: UUID
    periods: tuple[BillingPeriodRef, ...]
    invoice_date: date
    actor_id: UUID


@dataclass(frozen=True, slots=True, kw_only=True)
class InvoiceLineChange:
    """One line's new value. ``line_id=None`` creates a manual line (``InvoiceLineKind.MANUAL``,
    no ``project_id``/``billing_item_id``); given, it updates that line's editable fields without
    changing its ``kind``/``project_id``/``billing_item_id`` — so editing a generated line's
    description or price doesn't turn it into a manual one. ``amount`` is never part of the
    change — the service always recomputes it as ``quantity * unit_price``."""

    line_id: UUID | None
    description: str
    quantity: Decimal
    unit: str
    unit_price: Decimal


@dataclass(frozen=True, slots=True, kw_only=True)
class UpdateInvoiceDraft(Command[InvoiceDTO]):
    """Apply header field changes and a batch of line changes/deletes to ``invoice_id`` in one
    transaction, recomputing ``subtotal``/``vat_amount``/``total`` from the result.

    Every field left ``None`` is not changed; optional fields named in ``clear_fields`` are reset
    to ``None`` instead. Every line change is validated before any is applied, so a rejected batch
    leaves the invoice unchanged. Raises ``InvoiceNotFoundError``, ``InvoiceNotDraftError`` (only a
    draft is editable) or ``InvoiceLineNotFoundError``.
    """

    invoice_id: UUID
    actor_id: UUID
    invoice_date: date | None = None
    due_date: date | None = None
    vat_rate: Decimal | None = None
    vat_note: str | None = None
    your_reference: str | None = None
    notes: str | None = None
    lines: tuple[InvoiceLineChange, ...] = ()
    delete_line_ids: frozenset[UUID] = frozenset()
    clear_fields: frozenset[ClearableInvoiceField] = frozenset()


@dataclass(frozen=True, slots=True, kw_only=True)
class DeleteInvoiceDraft(Command[None]):
    """Delete a draft invoice and free every billing period it covered (a nested
    ``timesheets.ClearBillingPeriodsInvoiced``). Raises ``InvoiceNotFoundError`` or
    ``InvoiceNotDraftError``."""

    invoice_id: UUID
    actor_id: UUID


@dataclass(frozen=True, slots=True, kw_only=True)
class IssueInvoice(Command[InvoiceDTO]):
    """Move a draft to ``ISSUED``: allocates a number (``company.AllocateInvoiceNumber``),
    snapshots the current seller (company profile) and buyer (customer) so a later edit to either
    never changes what an already-issued invoice printed, renders the PDF and stores it with its
    SHA-256, all in this one transaction.

    Raises ``InvoiceNotFoundError``, ``InvoiceNotDraftError`` (only a draft can be issued),
    ``InvoiceEmptyError`` (no lines) or ``CompanyProfileIncompleteError`` (the company profile is
    missing an essential field, e.g. ``legal_name``/``org_number``).
    """

    invoice_id: UUID
    actor_id: UUID


@dataclass(frozen=True, slots=True, kw_only=True)
class MarkInvoicePaid(Command[InvoiceDTO]):
    """Move an issued invoice to ``PAID``. ``paid_on`` is supplied by the caller (a date picker on
    the frontend), never computed here. Raises ``InvoiceNotFoundError`` or
    ``InvoiceNotIssuedError`` (only an issued invoice can be marked paid)."""

    invoice_id: UUID
    actor_id: UUID
    paid_on: date


@dataclass(frozen=True, slots=True, kw_only=True)
class VoidInvoice(Command[InvoiceDTO]):
    """Move an issued or paid invoice to ``VOID`` and free every billing period it covered (a
    nested ``timesheets.ClearBillingPeriodsInvoiced``) — the number and PDF are kept as a record
    that this invoice number was used and then cancelled. Raises ``InvoiceNotFoundError`` or
    ``InvoiceNotVoidableError`` (a draft has nothing to void — delete it instead; an already-void
    invoice can't be voided again)."""

    invoice_id: UUID
    actor_id: UUID
    reason: str


# --- Exceptions ---


class InvoiceError(Exception):
    """Base class for invoices module domain errors."""


class InvoiceNotFoundError(InvoiceError):
    def __init__(self, invoice_id: UUID) -> None:
        super().__init__(f"Invoice {invoice_id} not found")
        self.invoice_id = invoice_id


class InvoiceCustomerNotFoundError(InvoiceError):
    def __init__(self, customer_id: UUID) -> None:
        super().__init__(f"Customer {customer_id} not found")
        self.customer_id = customer_id


class InvoiceNoPeriodsError(InvoiceError):
    def __init__(self) -> None:
        super().__init__("At least one billing period is required")


class InvoicePeriodNotEligibleError(InvoiceError):
    """Raised by ``CreateInvoiceDraft`` when a referenced period isn't sent, is already invoiced,
    is on an internal project, or doesn't belong to the invoice's customer."""

    def __init__(self, project_id: UUID, period_start: date, reason: str) -> None:
        super().__init__(
            f"Project {project_id}'s period starting {period_start} is not eligible for "
            f"invoicing: {reason}"
        )
        self.project_id = project_id
        self.period_start = period_start
        self.reason = reason


class BillingItemRateMissingError(InvoiceError):
    """Raised by ``CreateInvoiceDraft`` when an ``hour``/``day`` billing item used in the
    invoiced periods has no ``unit_rate`` set — ``items`` names every such item
    (``"<project> — <item>"``)."""

    def __init__(self, items: tuple[str, ...]) -> None:
        super().__init__(f"Missing a unit rate for: {', '.join(items)}")
        self.items = items


class InvoiceNotDraftError(InvoiceError):
    """Raised by ``UpdateInvoiceDraft``/``DeleteInvoiceDraft``/``IssueInvoice`` once the invoice
    has left ``DRAFT`` (issued invoices are immutable; see ``InvoiceStatus``)."""

    def __init__(self, invoice_id: UUID, status: InvoiceStatus) -> None:
        super().__init__(f"Invoice {invoice_id} is {status}, not draft")
        self.invoice_id = invoice_id
        self.status = status


class InvoiceLineNotFoundError(InvoiceError):
    def __init__(self, line_id: UUID) -> None:
        super().__init__(f"Invoice line {line_id} not found")
        self.line_id = line_id


class InvoiceEmptyError(InvoiceError):
    """Raised by ``IssueInvoice`` when the draft has no lines — nothing to bill."""

    def __init__(self, invoice_id: UUID) -> None:
        super().__init__(f"Invoice {invoice_id} has no lines")
        self.invoice_id = invoice_id


class CompanyProfileIncompleteError(InvoiceError):
    """Raised by ``IssueInvoice`` when the company profile (``company.CompanySettings``) is
    missing a field an invoice can't be printed without — ``fields`` names every such field."""

    def __init__(self, fields: tuple[str, ...]) -> None:
        super().__init__(f"Company profile is missing: {', '.join(fields)}")
        self.fields = fields


class InvoiceNotIssuedError(InvoiceError):
    """Raised by ``MarkInvoicePaid`` when the invoice isn't ``ISSUED`` (a draft has nothing to pay
    yet; a paid or void invoice can't be paid again)."""

    def __init__(self, invoice_id: UUID, status: InvoiceStatus) -> None:
        super().__init__(f"Invoice {invoice_id} is {status}, not issued")
        self.invoice_id = invoice_id
        self.status = status


class InvoiceNotVoidableError(InvoiceError):
    """Raised by ``VoidInvoice`` when the invoice is a draft (delete it instead) or already
    void."""

    def __init__(self, invoice_id: UUID, status: InvoiceStatus) -> None:
        super().__init__(f"Invoice {invoice_id} is {status} and can't be voided")
        self.invoice_id = invoice_id
        self.status = status
