"""Add projects.manager_id

Revision ID: e796661b995c
Revises: e4b6ff40d78b
Create Date: 2026-09-15 18:22:33.277594+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e796661b995c"
down_revision: str | Sequence[str] | None = "e4b6ff40d78b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("manager_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_projects_manager_id"), "projects", ["manager_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_projects_manager_id_users"),
        "projects",
        "users",
        ["manager_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_projects_manager_id_users"), "projects", type_="foreignkey")
    op.drop_index(op.f("ix_projects_manager_id"), table_name="projects")
    op.drop_column("projects", "manager_id")
    # ### end Alembic commands ###
