"""add company purchase flag to expense reports

Revision ID: a981372a1aca
Revises: fa056442428b
Create Date: 2026-09-30 22:37:13.054336+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a981372a1aca"
down_revision: str | Sequence[str] | None = "fa056442428b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "expense_reports",
        sa.Column(
            "company_purchase", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("expense_reports", "company_purchase")
    # ### end Alembic commands ###
