"""add project is_internal column

Revision ID: 9091d3b29f5a
Revises: 566f769e7284
Create Date: 2026-09-20 14:08:41.395750+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9091d3b29f5a"
down_revision: str | Sequence[str] | None = "566f769e7284"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("is_internal", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "is_internal")
    # ### end Alembic commands ###
