"""Add project_billing_periods table

Revision ID: b749088f080a
Revises: e796661b995c
Create Date: 2026-09-15 18:43:33.740730+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b749088f080a"
down_revision: str | Sequence[str] | None = "e796661b995c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_billing_periods",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "period_start <= period_end",
            name=op.f("ck_project_billing_periods_period_start_before_period_end"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_billing_periods_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sent_by_id"],
            ["users.id"],
            name=op.f("fk_project_billing_periods_sent_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_billing_periods")),
        sa.UniqueConstraint(
            "project_id", "period_start", name="uq_project_billing_periods_project_id_period_start"
        ),
    )
    op.create_index(
        op.f("ix_project_billing_periods_project_id"),
        "project_billing_periods",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_project_billing_periods_project_id"), table_name="project_billing_periods"
    )
    op.drop_table("project_billing_periods")
    # ### end Alembic commands ###
