"""add line_id to expense_attachments

Revision ID: 89e6d37b2498
Revises: 9917b1b6c101
Create Date: 2026-09-21 08:51:19.866359+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "89e6d37b2498"
down_revision: str | Sequence[str] | None = "9917b1b6c101"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("expense_attachments", sa.Column("line_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_expense_attachments_line_id"), "expense_attachments", ["line_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_expense_attachments_line_id_expense_report_lines"),
        "expense_attachments",
        "expense_report_lines",
        ["line_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_expense_attachments_line_id_expense_report_lines"),
        "expense_attachments",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_expense_attachments_line_id"), table_name="expense_attachments")
    op.drop_column("expense_attachments", "line_id")
    # ### end Alembic commands ###
