"""add rebilled expense report id to purchase documents

Revision ID: eeaba3d00c4b
Revises: a981372a1aca
Create Date: 2026-09-30 23:05:01.177342+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eeaba3d00c4b"
down_revision: str | Sequence[str] | None = "a981372a1aca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "purchase_documents", sa.Column("rebilled_expense_report_id", sa.Uuid(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_purchase_documents_rebilled_expense_report_id_expense_reports"),
        "purchase_documents",
        "expense_reports",
        ["rebilled_expense_report_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_purchase_documents_rebilled_expense_report_id_expense_reports"),
        "purchase_documents",
        type_="foreignkey",
    )
    op.drop_column("purchase_documents", "rebilled_expense_report_id")
    # ### end Alembic commands ###
