"""add article number to billing items and invoice lines

Revision ID: e71b4e70c954
Revises: c74b2ff851ad
Create Date: 2026-09-29 19:12:36.111465+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e71b4e70c954"
down_revision: str | Sequence[str] | None = "c74b2ff851ad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoice_lines", sa.Column("article_number", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "project_billing_items", sa.Column("article_number", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_billing_items", "article_number")
    op.drop_column("invoice_lines", "article_number")
    # ### end Alembic commands ###
