"""create non working days table

Revision ID: 04469e861ab0
Revises: 36657462fe83
Create Date: 2026-09-14 19:41:33.758323+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04469e861ab0"
down_revision: str | Sequence[str] | None = "36657462fe83"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "non_working_days",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("public_holiday", "bridge_day", "company_day_off", name="non_working_day_kind"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_non_working_days")),
        sa.UniqueConstraint("day", name="uq_non_working_days_day"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("non_working_days")
    # ### end Alembic commands ###
    # Autogenerate does not drop PostgreSQL enum types on downgrade.
    sa.Enum(name="non_working_day_kind").drop(op.get_bind(), checkfirst=True)
