"""add project billing period invoice id

Revision ID: 0cc794460b94
Revises: 6bcae2f1c157
Create Date: 2026-09-20 16:10:06.775389+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0cc794460b94"
down_revision: str | Sequence[str] | None = "6bcae2f1c157"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project_billing_periods", sa.Column("invoice_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_project_billing_periods_invoice_id"),
        "project_billing_periods",
        ["invoice_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_project_billing_periods_invoice_id"), table_name="project_billing_periods"
    )
    op.drop_column("project_billing_periods", "invoice_id")
    # ### end Alembic commands ###
