"""create project billing items table

Revision ID: 36657462fe83
Revises: 18106e13ec35
Create Date: 2026-09-14 11:50:28.339904+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "36657462fe83"
down_revision: str | Sequence[str] | None = "18106e13ec35"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# (preset, name, unit) — a literal copy of ``projects.contracts.DEFAULT_BILLING_ITEMS`` as of this
# revision, given to projects that already exist. Migrations never import application code.
DEFAULT_BILLING_ITEMS: tuple[tuple[str, str, str], ...] = (
    ("normal_hours", "Normal working hours", "hour"),
    ("overtime_hours", "Overtime working hours", "hour"),
    ("travel_time", "Travel time", "hour"),
    ("per_diem", "Per diems", "day"),
    ("purchasing_expenses", "Purchasing expenses", "amount"),
    ("other_expenses", "Other expenses", "amount"),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_billing_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "preset",
            sa.Enum(
                "normal_hours",
                "overtime_hours",
                "travel_time",
                "per_diem",
                "purchasing_expenses",
                "other_expenses",
                name="billing_item_preset",
            ),
            nullable=True,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("unit", sa.Enum("hour", "day", "amount", name="billing_unit"), nullable=False),
        sa.Column("unit_rate", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("markup_percent", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "markup_percent IS NULL OR unit = 'amount'",
            name=op.f("ck_project_billing_items_markup_percent_only_for_amount"),
        ),
        sa.CheckConstraint(
            "unit_rate IS NULL OR unit <> 'amount'",
            name=op.f("ck_project_billing_items_unit_rate_not_for_amount"),
        ),
        sa.CheckConstraint(
            "markup_percent >= 0", name=op.f("ck_project_billing_items_markup_percent_non_negative")
        ),
        sa.CheckConstraint(
            "unit_rate >= 0", name=op.f("ck_project_billing_items_unit_rate_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_billing_items_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_billing_items")),
        sa.UniqueConstraint("project_id", "name", name="uq_project_billing_items_project_id_name"),
        sa.UniqueConstraint(
            "project_id", "preset", name="uq_project_billing_items_project_id_preset"
        ),
    )
    # ### end Alembic commands ###

    for position, (preset, name, unit) in enumerate(DEFAULT_BILLING_ITEMS, start=1):
        op.execute(
            sa.text(
                "INSERT INTO project_billing_items (id, project_id, preset, name, unit, position) "
                "SELECT gen_random_uuid(), id, CAST(:preset AS billing_item_preset), :name, "
                "CAST(:unit AS billing_unit), :position FROM projects"
            ).bindparams(preset=preset, name=name, unit=unit, position=position)
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_billing_items")
    # ### end Alembic commands ###
    # Autogenerate does not drop PostgreSQL enum types on downgrade.
    sa.Enum(name="billing_unit").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="billing_item_preset").drop(op.get_bind(), checkfirst=True)
