"""Add company_settings table

Revision ID: 566f769e7284
Revises: 5e5dbf0870c9
Create Date: 2026-09-20 07:50:33.144949+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "566f769e7284"
down_revision: str | Sequence[str] | None = "5e5dbf0870c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("legal_name", sa.String(length=255), server_default="", nullable=False),
        sa.Column("org_number", sa.String(length=64), server_default="", nullable=False),
        sa.Column("vat_number", sa.String(length=64), server_default="", nullable=False),
        sa.Column("address_street", sa.String(length=255), server_default="", nullable=False),
        sa.Column("address_street2", sa.String(length=255), nullable=True),
        sa.Column("address_postal_code", sa.String(length=32), server_default="", nullable=False),
        sa.Column("address_city", sa.String(length=255), server_default="", nullable=False),
        sa.Column("address_country", sa.String(length=2), server_default="", nullable=False),
        sa.Column("email", sa.String(length=320), server_default="", nullable=False),
        sa.Column("phone", sa.String(length=64), server_default="", nullable=False),
        sa.Column("registered_office", sa.String(length=255), server_default="", nullable=False),
        sa.Column("bankgiro", sa.String(length=64), server_default="", nullable=False),
        sa.Column("iban", sa.String(length=64), server_default="", nullable=False),
        sa.Column("bic", sa.String(length=64), server_default="", nullable=False),
        sa.Column("f_tax_approved", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "default_invoice_locale", sa.String(length=2), server_default="sv", nullable=False
        ),
        sa.Column("late_interest", sa.String(length=255), server_default="", nullable=False),
        sa.Column("invoice_number_prefix", sa.String(length=20), server_default="", nullable=False),
        sa.Column("next_invoice_number", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "allow_self_review", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("logo", sa.LargeBinary(), nullable=True),
        sa.Column("logo_content_type", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "default_invoice_locale IN ('sv', 'en')",
            name=op.f("ck_company_settings_default_invoice_locale_valid"),
        ),
        sa.CheckConstraint(
            "logo_content_type IS NULL OR logo_content_type IN "
            "('image/svg+xml', 'image/png', 'image/jpeg')",
            name=op.f("ck_company_settings_logo_content_type_valid"),
        ),
        sa.CheckConstraint("id = 1", name=op.f("ck_company_settings_company_settings_singleton")),
        sa.CheckConstraint(
            "next_invoice_number > 0", name=op.f("ck_company_settings_next_invoice_number_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_settings")),
    )
    # ### end Alembic commands ###
    # The singleton row: every column but `id` relies on its server default.
    op.execute("INSERT INTO company_settings (id) VALUES (1)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("company_settings")
    # ### end Alembic commands ###
