"""create purchase documents table and company base currency

Revision ID: fa056442428b
Revises: 1dfc4ebcea42
Create Date: 2026-09-30 19:10:55.736021+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fa056442428b"
down_revision: str | Sequence[str] | None = "1dfc4ebcea42"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "purchase_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "stage",
            sa.Enum("inbox", "registered", "discarded", name="purchase_stage"),
            nullable=False,
        ),
        sa.Column(
            "kind",
            sa.Enum("receipt", "invoice", "card_invoice", "other", name="purchase_kind"),
            nullable=True,
        ),
        sa.Column("vendor", sa.String(length=255), nullable=True),
        sa.Column("document_no", sa.String(length=100), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("document_date", sa.Date(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column(
            "payment_status",
            sa.Enum("unpaid", "paid", name="purchase_payment_status"),
            nullable=True,
        ),
        sa.Column("paid_on", sa.Date(), nullable=True),
        sa.Column(
            "payment_method",
            sa.Enum(
                "card",
                "bank_transfer",
                "direct_debit",
                "cash",
                "private",
                name="purchase_payment_method",
            ),
            nullable=True,
        ),
        sa.Column("card_invoice_id", sa.Uuid(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.CHAR(length=3), nullable=True),
        sa.Column("vat_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("amount_base", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("exchange_rate", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("rate_date", sa.Date(), nullable=True),
        sa.Column(
            "rate_source",
            sa.Enum("none", "riksbank", "card_invoice", "manual", name="purchase_rate_source"),
            nullable=True,
        ),
        sa.Column(
            "amount_base_final", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.CHAR(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("source", sa.Enum("upload", "email", name="purchase_source"), nullable=False),
        sa.Column("email_from", sa.String(length=320), nullable=True),
        sa.Column("email_subject", sa.String(length=998), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("external_ref", sa.String(length=255), nullable=True),
        sa.Column("extracted", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rebilled_expense_line_id", sa.Uuid(), nullable=True),
        sa.Column("rebilled_expense_attachment_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("registered_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "card_invoice_id IS NULL OR payment_method = 'card'",
            name=op.f("ck_purchase_documents_card_invoice_needs_card"),
        ),
        sa.CheckConstraint(
            "due_date IS NULL OR kind IN ('invoice', 'card_invoice')",
            name=op.f("ck_purchase_documents_due_date_kind"),
        ),
        sa.CheckConstraint(
            "stage <> 'registered' OR kind IS NOT NULL",
            name=op.f("ck_purchase_documents_registered_has_kind"),
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_purchase_documents_size_positive")),
        sa.ForeignKeyConstraint(
            ["card_invoice_id"],
            ["purchase_documents.id"],
            name=op.f("fk_purchase_documents_card_invoice_id_purchase_documents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_purchase_documents_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["rebilled_expense_attachment_id"],
            ["expense_attachments.id"],
            name=op.f("fk_purchase_documents_rebilled_expense_attachment_id_expense_attachments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["rebilled_expense_line_id"],
            ["expense_report_lines.id"],
            name=op.f("fk_purchase_documents_rebilled_expense_line_id_expense_report_lines"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["registered_by_id"],
            ["users.id"],
            name=op.f("fk_purchase_documents_registered_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_documents")),
        sa.UniqueConstraint("external_ref", name=op.f("uq_purchase_documents_external_ref")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_purchase_documents_storage_key")),
    )
    op.create_index(
        op.f("ix_purchase_documents_card_invoice_id"),
        "purchase_documents",
        ["card_invoice_id"],
        unique=False,
    )
    op.create_index(
        "ix_purchase_documents_document_date", "purchase_documents", ["document_date"], unique=False
    )
    op.create_index(
        "ix_purchase_documents_payment_status_due_date",
        "purchase_documents",
        ["payment_status", "due_date"],
        unique=False,
    )
    op.create_index(
        "ix_purchase_documents_stage_kind", "purchase_documents", ["stage", "kind"], unique=False
    )
    op.add_column(
        "company_settings",
        sa.Column("base_currency", sa.String(length=3), server_default="SEK", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company_settings", "base_currency")
    op.drop_index("ix_purchase_documents_stage_kind", table_name="purchase_documents")
    op.drop_index("ix_purchase_documents_payment_status_due_date", table_name="purchase_documents")
    op.drop_index("ix_purchase_documents_document_date", table_name="purchase_documents")
    op.drop_index(op.f("ix_purchase_documents_card_invoice_id"), table_name="purchase_documents")
    op.drop_table("purchase_documents")
    # Autogenerate leaves the native enum types behind.
    for enum_name in (
        "purchase_stage",
        "purchase_kind",
        "purchase_payment_status",
        "purchase_payment_method",
        "purchase_rate_source",
        "purchase_source",
    ):
        op.execute(f"DROP TYPE {enum_name}")
    # ### end Alembic commands ###
