"""create time entries table

Revision ID: 7e0c5c5a784f
Revises: 04469e861ab0
Create Date: 2026-09-14 20:01:06.771464+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# The `billing_unit` Postgres enum already exists (created by the project_billing_items
# migration); this table reuses it, so `create_type=False` keeps `op.create_table` from trying to
# create it again.
_BILLING_UNIT = postgresql.ENUM("hour", "day", "amount", name="billing_unit", create_type=False)

# revision identifiers, used by Alembic.
revision: str = "7e0c5c5a784f"
down_revision: str | Sequence[str] | None = "04469e861ab0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "time_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("billing_item_id", sa.Uuid(), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("unit", _BILLING_UNIT, nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_time_entries_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["billing_item_id"],
            ["project_billing_items.id"],
            name=op.f("fk_time_entries_billing_item_id_project_billing_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_time_entries_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_time_entries_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_time_entries")),
        sa.UniqueConstraint(
            "user_id",
            "billing_item_id",
            "entry_date",
            name="uq_time_entries_user_id_billing_item_id_entry_date",
        ),
    )
    op.create_index(
        op.f("ix_time_entries_project_id"), "time_entries", ["project_id"], unique=False
    )
    op.create_index(
        "ix_time_entries_user_id_entry_date",
        "time_entries",
        ["user_id", "entry_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_time_entries_user_id_entry_date", table_name="time_entries")
    op.drop_index(op.f("ix_time_entries_project_id"), table_name="time_entries")
    op.drop_table("time_entries")
    # ### end Alembic commands ###
