"""Add expense_attachments table

Revision ID: ec972f2ca14b
Revises: ca30ab18d443
Create Date: 2026-09-17 23:33:02.948103+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec972f2ca14b"
down_revision: str | Sequence[str] | None = "ca30ab18d443"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expense_attachments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("uploaded_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["expense_reports.id"],
            name=op.f("fk_expense_attachments_report_id_expense_reports"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["users.id"],
            name=op.f("fk_expense_attachments_uploaded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expense_attachments")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_expense_attachments_storage_key")),
    )
    op.create_index(
        op.f("ix_expense_attachments_report_id"), "expense_attachments", ["report_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_expense_attachments_report_id"), table_name="expense_attachments")
    op.drop_table("expense_attachments")
    # ### end Alembic commands ###
