"""create customers table

Revision ID: afc8487ee019
Revises: e9d62f939535
Create Date: 2026-09-13 23:03:56.157059+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "afc8487ee019"
down_revision: str | Sequence[str] | None = "e9d62f939535"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("legal_name", sa.String(length=255), nullable=True),
        sa.Column("tax_id", sa.String(length=64), nullable=True),
        sa.Column("billing_email", sa.String(length=320), nullable=True),
        sa.Column("billing_address_line1", sa.String(length=255), nullable=False),
        sa.Column("billing_address_line2", sa.String(length=255), nullable=True),
        sa.Column("billing_city", sa.String(length=255), nullable=False),
        sa.Column("billing_region", sa.String(length=255), nullable=True),
        sa.Column("billing_postal_code", sa.String(length=32), nullable=True),
        sa.Column("billing_country", sa.String(length=2), nullable=False),
        sa.Column("billing_interval_count", sa.Integer(), nullable=False),
        sa.Column(
            "billing_interval_unit",
            sa.Enum("day", "week", "month", "year", name="billing_interval_unit"),
            nullable=False,
        ),
        sa.Column("billing_anchor_date", sa.Date(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("payment_terms_days", sa.Integer(), server_default="30", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "billing_interval_count > 0", name=op.f("ck_customers_billing_interval_count_positive")
        ),
        sa.CheckConstraint(
            "payment_terms_days >= 0", name=op.f("ck_customers_payment_terms_days_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("name", name=op.f("uq_customers_name")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("customers")
    # ### end Alembic commands ###
    # Autogenerate does not drop PostgreSQL enum types on downgrade.
    sa.Enum(name="billing_interval_unit").drop(op.get_bind(), checkfirst=True)
