"""Add expense_reports and expense_report_lines tables

Revision ID: ca30ab18d443
Revises: c445439df391
Create Date: 2026-09-17 23:16:21.106775+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca30ab18d443"
down_revision: str | Sequence[str] | None = "c445439df391"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expense_reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "submitted", "approved", "returned", name="expense_report_status"),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by_id", sa.Uuid(), nullable=True),
        sa.Column("return_comment", sa.String(length=10000), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "period_start <= period_end",
            name=op.f("ck_expense_reports_period_start_before_period_end"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_expense_reports_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"],
            ["users.id"],
            name=op.f("fk_expense_reports_reviewed_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_expense_reports_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expense_reports")),
        sa.UniqueConstraint(
            "user_id",
            "project_id",
            "period_start",
            name="uq_expense_reports_user_id_project_id_period_start",
        ),
    )
    op.create_index(
        "ix_expense_reports_project_id_period_start",
        "expense_reports",
        ["project_id", "period_start"],
        unique=False,
    )
    op.create_table(
        "expense_report_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("billing_item_id", sa.Uuid(), nullable=False),
        sa.Column("expense_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("vendor", sa.String(length=255), nullable=True),
        sa.Column("document_no", sa.String(length=100), nullable=True),
        sa.Column("position", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_expense_report_lines_amount_positive")),
        sa.ForeignKeyConstraint(
            ["billing_item_id"],
            ["project_billing_items.id"],
            name=op.f("fk_expense_report_lines_billing_item_id_project_billing_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["expense_reports.id"],
            name=op.f("fk_expense_report_lines_report_id_expense_reports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expense_report_lines")),
    )
    op.create_index(
        op.f("ix_expense_report_lines_report_id"),
        "expense_report_lines",
        ["report_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_expense_report_lines_report_id"), table_name="expense_report_lines")
    op.drop_table("expense_report_lines")
    op.drop_index("ix_expense_reports_project_id_period_start", table_name="expense_reports")
    op.drop_table("expense_reports")
    # ### end Alembic commands ###
    # Autogenerate does not drop PostgreSQL enum types on downgrade.
    sa.Enum(name="expense_report_status").drop(op.get_bind(), checkfirst=True)
