"""add timesheet weeks and row comments, project normal working hours

Revision ID: e4b6ff40d78b
Revises: 7e0c5c5a784f
Create Date: 2026-09-15 11:57:41.137843+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e4b6ff40d78b"
down_revision: str | Sequence[str] | None = "7e0c5c5a784f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "timesheet_weeks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "submitted", "approved", "returned", name="timesheet_week_status"),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by_id", sa.Uuid(), nullable=True),
        sa.Column("return_comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"],
            ["users.id"],
            name=op.f("fk_timesheet_weeks_reviewed_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_timesheet_weeks_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_timesheet_weeks")),
        sa.UniqueConstraint("user_id", "week_start", name="uq_timesheet_weeks_user_id_week_start"),
    )
    op.create_index("ix_timesheet_weeks_status", "timesheet_weeks", ["status"], unique=False)
    op.create_table(
        "timesheet_row_comments",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("billing_item_id", sa.Uuid(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["billing_item_id"],
            ["project_billing_items.id"],
            name=op.f("fk_timesheet_row_comments_billing_item_id_project_billing_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_timesheet_row_comments_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "week_start", "billing_item_id", name=op.f("pk_timesheet_row_comments")
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "normal_working_hours",
            sa.Numeric(precision=4, scale=2),
            server_default="8",
            nullable=False,
        ),
    )
    # Autogenerate doesn't add CHECK constraints for a new column; added by hand.
    op.create_check_constraint(
        op.f("ck_projects_normal_working_hours_range"),
        "projects",
        "normal_working_hours > 0 AND normal_working_hours <= 24",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_projects_normal_working_hours_range"), "projects", type_="check")
    op.drop_column("projects", "normal_working_hours")
    op.drop_table("timesheet_row_comments")
    op.drop_index("ix_timesheet_weeks_status", table_name="timesheet_weeks")
    op.drop_table("timesheet_weeks")
    # ### end Alembic commands ###
    # Autogenerate does not drop PostgreSQL enum types on downgrade.
    sa.Enum(name="timesheet_week_status").drop(op.get_bind(), checkfirst=True)
